name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e ".[docs]"

    - name: Build documentation
      run: |
        cd docs
        uv run sphinx-build -b html . _build/html

